CLASS zbp_zad_r_orderingtp_extension DEFINITION PUBLIC ABSTRACT FINAL for BEHAVIOR OF ZAD_R_ORDERINGTP.

protected section.
private section.
ENDCLASS.



CLASS ZBP_ZAD_R_ORDERINGTP_EXTENSION IMPLEMENTATION.
ENDCLASS.
